language: python
python:
  - "2.7"

#to start mongodb in travis
services:
  - mongodb

#Django & Database
env:
  -DJANGO=1.7.4 DB=mysql
  -DJANGO=1.7.4 DB=sqlite3

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install mysql-python --use-mirrors


# command to run tests
script:
  - python manage.py test
  - coverage run --source=mslice manage.py test

#submiting result to coverals.io
after_success:
  coveralls

# .travis.yml
before_script:
  - mongo slice --eval 'db.addUser("root", "root");'